### PR TITLE
Use smart-contract in Golang

### PR DESCRIPTION
**Pull request by fyrchik**
Draft, because under testing currently.

### CODE REVIEW

**Comment by roman-khimov** [comment]
AVM? I expected to see some `.go` here and a make incantation to build an avm from that using neo-go.

**Comment by anatoly-bogatyrev** [comment]
@roman-khimov In this repository, we do not store the source code of the test smart contract. Only .avm.

**Comment by alexvanin** [comment]
I think `Deposit` call doesn't work as expected. When I invoked it, CGAS assets were not transferred to the smart-contract address, even though I got message `funds have been transfered` (typo there).

```
neo> sc invoke 0xdb674de13525119761d8b9bd553ae24127b1b920 Deposit [b'031a6c6fbbdf02ca351745fa86b9ba5a9452d785ac4f7fc2b7548ca2a46c4fcf4a', 1234]
[I 200207 12:43:27 EventHub:58] [test_mode][SmartContract.Runtime.Log] [db674de13525119761d8b9bd553ae24127b1b920] {'type': 'String', 'value': 'funds have been transfered'}
[I 200207 12:43:27 EventHub:58] [test_mode][SmartContract.Execution.Success] [db674de13525119761d8b9bd553ae24127b1b920] {'type': 'Array', 'value': [{'type': 'Integer', 'value': '1'}]}
Used 0.47 Gas 

-------------------------------------------------------------------------------------------------------------------------------------
Test invoke successful
Total operations: 367
Results [{'type': 'Integer', 'value': '1'}]
Invoke TX GAS cost: 0.0
Invoke TX fee: 0.0001
-------------------------------------------------------------------------------------------------------------------------------------

Enter your password to continue and deploy this contract
[password]> ***
[I 200207 12:43:28 Transaction:619] Verifying transaction: b'ba38762815848893f2d3eb6acf264793939f91fb2284ae96d7dc4e80b57cffc8' 
[I 200207 12:43:28 EventHub:62] [SmartContract.Verification.Success][4039] [8da979726da87403daf85668e220927b824a4cf4] [tx ba38762815848893f2d3eb6acf264793939f91fb2284ae96d7dc4e80b57cffc8] {'type': 'Array', 'value': [{'type': 'Boolean', 'value': True}]}
Relayed Tx: ba38762815848893f2d3eb6acf264793939f91fb2284ae96d7dc4e80b57cffc8 
neo>
neo>
neo> [I 200207 12:43:42 EventHub:62] [SmartContract.Runtime.Log][4039] [db674de13525119761d8b9bd553ae24127b1b920] [tx ba38762815848893f2d3eb6acf264793939f91fb2284ae96d7dc4e80b57cffc8] {'type': 'String', 'value': 'funds have been transfered'}
[I 200207 12:43:42 EventHub:62] [SmartContract.Execution.Success][4039] [db674de13525119761d8b9bd553ae24127b1b920] [tx ba38762815848893f2d3eb6acf264793939f91fb2284ae96d7dc4e80b57cffc8] {'type': 'Array', 'value': [{'type': 'Integer', 'value': '1'}]}
```

**Comment by fyrchik** [comment]
There are 2 bugs:
1. CGAS contract returns a string if an unknown operation was provided. This string is converted to `true` in a calling contract.
2. Wrong order of arguments on stack after invoking `AppCall`.

**Comment by alexvanin** [comment]
What do you think about updating default smart-contract script hash in  `neofs-local/neofs-local/.env`?
```
#NEOFS_SMART_CONTRACT_HASH=0xe09b9077a099cebb1ae870b5128e44359001c6a7
```

**Review by alexvanin — APPROVED** [review]

**Review by im-kulikov — APPROVED** [review]

**Pull request merged**
